### ISSUE TITLE
sibilings parameter working strangely in v1

### ISSUE THREAD

**Issue by nippur72** [ultimate-pagination/ultimate-pagination#15]
after upgrading to v1 and starting to use the new `siblingPagesRange` the current page marker is no longer centered respect to its sibilings.

Examples:

with `siblingPagesRange: 1`
![immagine1](https://cloud.githubusercontent.com/assets/2598443/23104560/74d7e816-f6d0-11e6-8c1b-a42f6763e78e.png)
it should be: .., 36, (37), 38, ..

with `siblingPagesRange: 5`
![immagine2](https://cloud.githubusercontent.com/assets/2598443/23104561/77e5e346-f6d0-11e6-889d-d7ce44800c40.png)
see how there are 6 items before "16" but only 4 items after.

**Comment by dmytroyarmak** [comment]
Hey @nippur72 
I've tried these parameters in unit tests and here is what I got:

1. For first example
```
getPaginationModel({ currentPage: 37, totalPages: 64, siblingPagesRange: 1 });
```
```
["1(<<)", "36(<)", "1", "35(<...)", "36", "*37", "38", "39(...>)", "64", "38(>)", "64(>>)"]
```

2. For the second example
```
getPaginationModel({ currentPage: 16, totalPages: 64, siblingPagesRange: 5 });
```
```
["1(<<)", "15(<)", "1", "10(<...)", "11", "12", "13", "14", "15", "*16", "17", "18", "19", "20", "21", "22(...>)", "64", "17(>)", "64(>>)"]
```

Can you please check what are inputs and outputs for `getPaginationModel` in your case? I haven't updated any integration to the `v1.0.0` so I can't test it on the page.

**Comment by dmytroyarmak** [comment]
Here I've updated an example with react binding and it looks fine: http://ultimate-pagination.github.io/react-ultimate-pagination-examples/

**Comment by nippur72** [comment]
sorry there was a mistake in my code 😳 now all is working, thank you for the nice improvement!

**Comment by dmytroyarmak** [comment]
you are welcome :)
