### ISSUE TITLE
minor trouble with TypeScript and Webpack

### ISSUE THREAD

**Issue by nippur72** [ultimate-pagination/ultimate-pagination#2]
I use this lib in `typescript` with something like this:
```ts
import * as ult from "ultimate-pagination";
...
let x = ult.getPaginationModel({ totalPages: 50, currentPage: 10});
```
and then I bundle with `webpack`. 

The problem is that I get this annoying warning from webpack:
```
WARNING in ./~/ultimate-pagination/lib/ultimate-pagination.js                                                                     
Cannot find source file '../src/ultimate-pagination.ts': Error: Can't resolve '../src/ultimate-pagination.ts' in 'C:\Users\Nino\De
sktop\USB\presenze\node_modules\ultimate-pagination\lib'                                                  
 @ ./src/tags/richiesta-ferie/elenco/elenco-richieste.ts 5:10-40                                                                  
 @ ./src/tags/main-tag/main-tag.html                                                                                              
 @ ./src/app.ts                      
```
Do you have any idea what could be the cause? I use other typescript-based libraries without problems.

My guess it's something with the `lib` directory being processed by webpack/ts-loader for some reason...

BTW you should mention that typescript developers can use the `.d.ts` typings as well :-)

BTW.2 awesome tool, when you need it, you really need it!

**Comment by dmytroyarmak** [comment]
@nippur72 What version of `typescript` and `webpack` do you use?

**Comment by nippur72** [comment]
Typescript: Version 2.2.0 (release candidate)
Webpack: 2.2.1 with `ts-loader` 2.2.0

**Comment by dmytroyarmak** [comment]
I think I know where is a problem, looks like `webpack` is trying to "repackage" `sourcemap` but it can't do it because I don't ship `src` folder in npm package.
I'll make sure that it works fine in next release.

**Comment by nippur72** [comment]
Yes, I think it will be enough to turn off sourcemaps for the npm package. I manually removed all references to sourcemaps and it's ok now.

Also in `package.json` I think you should have:
```
"main": "dist/ultimate-pagination.js",
```
instead of 
```
"main": "lib/ultimate-pagination.js",
```

**Comment by dmytroyarmak** [comment]
I'm not sure about changing `"main"` to a bundled version of the library. 
I think it still should be an entry point for transpiled but not bundled code. In this case, you will have a more flat bundle in your app (webpack will create a wrapper for modules only once and it will be on your app level).
